[theme]
base = "light"
primaryColor = "#2c3e50"
backgroundColor = "#f9f9f9"
secondaryBackgroundColor = "#eaeaea"
textColor = "#212121"
font = "Helvetica"
font_size = 14
font_weight = "normal"
lineHeight = 1.5
pageWidth = 1000
pageBackgroundColor = "#f9f9f9"
sidebarBackgroundColor = "#2c3e50"
headerColor = "#2c3e50"
buttonBackgroundColor = "#2c3e50"
buttonTextColor = "#ffffff"
warningBackgroundColor = "#f6b93b"
warningTextColor = "#ffffff"
box_shadow = True
border_radius = 4