[theme]
base = "dark"
primaryColor = "#0077c2"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2f2f2"
textColor = "#333333"
font = "Helvetica"
font_size = 14
font_weight = "normal"
lineHeight = 1.5
pageWidth = 1000
pageBackgroundColor = "#ffffff"
sidebarBackgroundColor = "#0077c2"
headerColor = "#0077c2"
buttonBackgroundColor = "#0077c2"
buttonTextColor = "#ffffff"
warningBackgroundColor = "#FFDAB9"
warningTextColor = "#333333"
box_shadow = true
border_radius = 4