[theme]
base = "light"
buttonBackgroundColor = "#0077c2"
buttonTextColor = "#ffffff"
textColor = "272525"
font = "Helvetica"
font_size = 14
font_weight = "normal"
lineHeight = 1.5
pageWidth = 1000
backgroundColor = "#FBF8F5"
secondaryBackgroundColor = "#f2f2f2"

