[theme]
base = "light"
primaryColor = "#2962FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#333333"
font = "Arial"
font_size = 16
font_weight = "normal"
lineHeight = 1.5
pageWidth = 960
pageBackgroundColor = "#FFFFFF"
sidebarBackgroundColor = "#F5F5F5"
headerColor = "#2962FF"
buttonBackgroundColor = "#2962FF"
buttonTextColor = "#FFFFFF"
warningBackgroundColor = "#FFE082"
warningTextColor = "#333333"
box_shadow = true
border_radius = 4

